#!/usr/bin/env bash
set -e

sudo apt-get remove docker docker-engine docker.io containerd runc | true
sudo apt-get update
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

sudo docker run hello-world
sudo systemctl is-active docker
sudo systemctl is-enabled docker
echo "sudo usermod -aG docker $(id -u -n)"
